### ISSUE TITLE
Upgrade from Javascript to Typescript

### ISSUE THREAD

**Issue by tiennampham23** [leducthang98/TFilm#1]
I think you should use Typescript instead of Javascript. Javascript is fucking shit!!!!

**Comment by leducthang98** [comment]
Khang cũng có nói về chuyện qua ts rồi. Cơ mà tớ nghĩ nhé, nếu project tớ cần nhanh gọn thì sẽ dùng js, còn nếu cần chặt chẽ t sẽ dùng hẳn java luôn ấy, như vậy thì nó rõ ràng về lợi ích của 2 loại ngôn ngữ hơn :D

**Comment by tiennampham23** [comment]
Typescript nó vừa có tác dụng của Java mà cũng vừa có JS. Cơ bản thì nếu code JS quen thì các libraries support JS đều work với @type trên Typescript =))).
Java thì libraries mới hoàn toàn, code dài hơn và config mất thời gian hơn.

**Comment by tiennampham23** [comment]
Code JS lúc dò typing của 1 object nào đó toàn phải console.log hoặc debug, khổ như dog 🥲

**Comment by leducthang98** [comment]
ừa, để sau đợt này đi làm học dần TS luôn
